version: '3.8'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - appnet
    working_dir: /var/www/html
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
    depends_on:
      - app
  
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  pgadmin:
      image: dpage/pgadmin4
      ports:
          - 5050:80
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      restart: unless-stopped
      networks:
        - appnet
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      depends_on:
        - db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  appnet: